import { Inter } from "next/font/google";
import "./globals.css";
import Providor from "./Providor";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Providor>{children}</Providor>
        </body>
      </html>
    </ClerkProvider>
  );
}
